name: Deploy on VPS

on:
  push:
    tags:
      - v* 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurazione SSH per connettersi al VPS
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

    # Deploy sul VPS
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
          set -e  # Interrompe lo script in caso di errore
          echo "Navigating to project directory..."
          cd /var/www/docker/build/personal_site_v2 || { echo "Failed to navigate to project directory"; exit 1; }
          
          echo "Pulling latest changes from Git..."
          git pull origin main || { echo "Git pull failed"; exit 1; }
          
          echo "Building Docker image..."
          docker build -t personal_site_v2:latest . || { echo "Docker build failed"; exit 1; }
          
          echo "Restarting Docker Compose services..."
          cd .. || { echo "Failed to navigate to parent directory"; exit 1; }
          docker-compose down || { echo "Docker Compose down failed"; exit 1; }
          docker-compose up -d || { echo "Docker Compose up failed"; exit 1; }
          
          echo "Deployment completed successfully!"
        EOF